export { default as img_top_1 } from "./The Witcher 3.jpg";
export { default as img_top_2 } from "./Red_Dead_Redemption_2_coverart.jpg";
export { default as img_top_3 } from "./Forza 5.png";
export { default as img_top_4 } from "./atomic heart.jpg";
export { default as img_top_5 } from "./Counter Strike 2 card.jpg";
export { default as img_top_6 } from "./gta5.png";
export { default as img_top_7 } from "./assasins_creed.jpg";
export { default as img_top_8 } from "./spider man.jpg";
export { default as img_top_9 } from "./mirage.jpg";
export { default as img_top_10 } from "./valhalla.png";
export { default as img_top_11 } from "./ark.jpg";
export { default as img_top_12 } from "./fifa.png";
export { default as img_top_13 } from "./dirt5.jpg";
export { default as img_top_14 } from "./cyberpank.jpg";
export { default as img_top_15 } from "./empires4.jpg";
export { default as img_top_16 } from "./civilisation.jpg";
export { default as windows } from "../images/windows.png";


export { default as sales_game1 } from "./How to Survive.jpg";
export { default as sales_game2 } from "./Red Solstice 2 Survivors.jpg";
export { default as leaders_game1 } from "./Counter Strike 2 card.jpg";
export { default as leaders_game2 } from "./Elden Ring card.jpg";
export { default as leaders_game3 } from "./Pubg Battlegrounds.jpg";
export { default as leaders_game4 } from "./The Witcher 3.jpg";
export { default as leaders_game5 } from "./atomic heart.jpg";
export { default as leaders_game6 } from "./crab game.jpg";
export { default as new_game1 } from "./alpha league.jpg";
export { default as new_game2 } from "./sons of the forests.jpg";
export { default as new_game3 } from "./pacific drive.jpg";